import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import Modal from "./components/modal/Modal";
import LoginModal from "./components/modal/LoginModal";
import SighnupModal from "./components/modal/SignupModal";
import AddPropertyModal from "./components/modal/AddPropertyModal";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import SearchModal from "./components/modal/SearchModal";
import EditProfileModal from "./components/modal/EditProfileModal";
import EditPropertyModal from "./components/modal/EditPropertyModal";
import PaymentProccessModal from "./components/modal/PaymentProccessModal";
import { NotificationProvider } from "./components/context/NotificationContext";
import { getUserId,getAccessToken } from "./lib/actions";
import { WebSocketProvider } from "./components/context/WebSocketProvider";



const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Djangobnb",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>
)

 {
  const userId = await getUserId(); // from auth/session
  const token = await getAccessToken(); // from auth/session
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <WebSocketProvider token={token ?? null} userId={userId}>
          <NotificationProvider>
            <Navbar />
            <div className="pt-28">{children}</div>
            {/* <Modal label="test" content={content} isOpen={false}/> */}
            <LoginModal />
            <SighnupModal />
            <AddPropertyModal />
            <SearchModal />
            <PaymentProccessModal />
            {/* <EditProfileModal/> */}
            <ToastContainer />
          </NotificationProvider>
        </WebSocketProvider>
      </body>
    </html>
  );
}
