import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import Modal from "./components/modal/Modal";
import LoginModal from "./components/modal/LoginModal";
import SighnupModal from "./components/modal/SignupModal";
import AddPropertyModal from "./components/modal/AddPropertyModal";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import SearchModal from "./components/modal/SearchModal";
import EditProfileModal from "./components/modal/EditProfileModal";
import EditPropertyModal from "./components/modal/EditPropertyModal";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Djangobnb",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <div className="pt-28">{children}</div>
        {/* <Modal label="test" content={content} isOpen={false}/> */}
        <LoginModal/>
        <SighnupModal/>
        <AddPropertyModal/>
        <SearchModal/>
        <EditPropertyModal/>
        {/* <EditProfileModal/> */}
        <ToastContainer/>
      </body>
    </html>
  );
}
